jenkins:
  systemMessage: "Jenkins configured with Configuration as Code"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - file: /usr/share/jenkins/ref/seed_job.groovy